---
language: python

sudo: required

dist: xenial

python: "3.7"

install:
  - sudo apt install -y git jq
  - pip install -r https://raw.githubusercontent.com/nephelaiio/ansible-role-requirements/master/requirements.txt

stages:
  - test
  - deploy

jobs:
  include:
    - script:
        - yamllint ./ -c ./.yamllint
        - flake8 ./
      stage: test
    - script:
        - ./bin/awx_update_projects.sh --host $AWX_URL --user $AWX_USER --pass $AWX_PASS --repo https://github.com/$TRAVIS_REPO_SLUG.git --debug
        - ./bin/awx_run_templates.sh --host $AWX_URL --user $AWX_USER --pass $AWX_PASS --repo https://github.com/$TRAVIS_REPO_SLUG.git --debug
      stage:
        deploy

branches:
  only:
    - master
