---
language: python

sudo: required

dist: xenial

git:
  submodules: false

python: "3.7"

install:
  - sudo apt install -y git jq
  - pip install -r https://raw.githubusercontent.com/nephelaiio/ansible-role-requirements/master/requirements.txt
  - git clone https://github.com/basherpm/basher.git ~/.basher
  - export PATH="$HOME/.basher/bin:$PATH"
  - eval "$(basher init -)"
  - basher install nephelaiio/basher-awx

stages:
  - lint

jobs:
  include:
    - script:
        - yamllint ./ -c ./.yamllint
        - flake8 ./
      stage: lint

branches:
  only:
    - master
