---
language: python

sudo: required

install:
  - sudo pip install yamllint
  - sudo pip install flake8

script:
  - yamllint ./ -c ./.yamllint
  - flake8 ./
  - ./bin/awx_update_project.sh --url $AWX_URL --user $AWX_USER --pass $AWX_PASS --repo https://github.com/$TRAVIS_REPO_SLUG.git

branches:
  only:
    - master
