---
- src: nginxinc.nginx
  version: 0.12.0
- src: nephelaiio.plugins
  version: 1.0.9
- src: nephelaiio.docker
  version: 4.0.3
- src: nephelaiio.pip
  version: 4.0.1
- src: nephelaiio.acme_certificate_route53
  version: 1.0.0
